# Generated by Django 4.1.10 on 2023-08-12 23:47

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question", name="choices", field=jsonfield.fields.JSONField(),
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answers", jsonfield.fields.JSONField(blank=True, null=True)),
                (
                    "QuestionAssignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.questionassignment",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.exam"
                    ),
                ),
            ],
        ),
    ]
