# Generated by Django 4.1.10 on 2023-09-29 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_question_choices_studentanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.exam",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="semester",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subject",
            name="id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
