# Generated by Django 4.1.10 on 2024-02-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_examsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("PUBLISHED", "Published"),
                    ("STARTED", "Started"),
                    ("ENDED", "Ended"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
    ]
