# Generated by Django 4.1.10 on 2023-09-29 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_question_choices_alter_question_exam_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exam",
            name="datetime_published",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="marksPerQuestion",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="negativeMarks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="passingMarks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam", name="totalMarks", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="totalQuestions",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
