# Generated by Django 4.1.10 on 2023-09-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_exam_created_by_exam_datetime_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="semester",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
