# Generated by Django 4.1.11 on 2023-09-30 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='QuestionAssignment',
            new_name='question_assignment',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='exam',
        ),
        migrations.AddField(
            model_name='examresult',
            name='total_attempted',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='total_correct_answers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_choices',
            field=models.ManyToManyField(related_name='selected_answers', to='api.choice'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'exam')},
        ),
    ]
