# Generated by Django 4.1.11 on 2023-12-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_questionassignment_studentanswer_question_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='question_assignment',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='selected_choices',
        ),
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='choices/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.DeleteModel(
            name='ExamResult',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
